### ISSUE TITLE
Bestätigungsemail soll sprachspezifisch verschickt werden

### ISSUE THREAD

**Issue by mdahinden** [Educational-Engineering/Issues#13]
Entweder sollte man bei der Anmeldung die Sprache erfragen oder man übernimmt einfach die vom Benutzer im UI eingestellte Sprache.

Aus Gründen der Einfachheit würde ich Letzteres machen.

**Comment by DavidSichau** [comment]
Dies ist leider ein grösseres Problem, da ich das Email Template auf dem Server rendern muss. Da dieser stateless ist, habe ich keine Information darüber welcher Benutzer welche Sprache ausgewählt hat.

Die einfachste Lösung wäre die Email in allen Sprachen zu generieren.
