### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by miraamis** [Educational-Engineering/Issues#18]
Text, der mit Backtick-Zeichen umschlossen ist, wird nicht farbig angezeigt.

**Comment by DavidSichau** [comment]
Dies ist eine bewusste Änderung zum alten System.

Bei inline Code, ist es schwierig die Sprache korrekt zu erkennen. Daher wird das Syntax hightlighting ausgeschaltet.

Die Farbe des Codes wurde auch geändert auf grau.

Ist der Code dadurch schlechter lesbar?

**Comment by miraamis** [comment]
Ach so, das war mir nicht bewusst. 

Nein, der Code ist nicht schlechter lesbar.
