### ISSUE TITLE
Darstellungsfehler in spanischen Versionen

### ISSUE THREAD

**Issue by miraamis** [Educational-Engineering/Issues#26]
In der Vorschau wird nicht angezeigt bei welchem Schritt man sich gerade befindet. Bei der Auswahl der Tools ist die Darstellung unschön. Das gleiche beim Button ganz unten um zum nächsten Schritt zu gelangen. Ausserdem wurden in den spanischen Versionen die Kapitelüberschriften und die Inhalte in Grafiken (z.B. Achsenbeschriftungen) oft nicht übersetzt.

![darstellungsfehler in spanischer version](https://cloud.githubusercontent.com/assets/11815396/7428222/cb915774-efec-11e4-8bfd-662366d29288.png)

**Comment by DavidSichau** [comment]
Hallo, dies liegt daran,  dass die spanische Version noch nicht übersetzt ist.  Im Moment ist dies bei der Übersetzerin.
