### ISSUE TITLE
MathJax Integration

### ISSUE THREAD

**Issue by knsimon** [Educational-Engineering/Issues#27]
Es wäre cool, wenn ihr auf eurem Testserver MathJax integrieren könntet. Möglicherweise ist der Aufwand dafür sehr gering. Auf einer üblichen Webseite reicht ein script-Eintrag im head:
http://docs.mathjax.org/en/latest/start.html

Nachher wird E.Tutorial wunderbare Formeln einzeigen können, beispielsweise so:

![screenshot from 2015-05-11 15 57 17](https://cloud.githubusercontent.com/assets/12395726/7566516/89fd7cf8-f7f7-11e4-9527-1dcdc93e9749.png)

**Comment by DavidSichau** [comment]
Ich werde es einmal anschauen.

Es ist leider nicht ganz so trivial, da wir MathJax zuerst durch den Markdown Parser hindurch schleusen müssen, ohne dass es verändert wird.

**Comment by DavidSichau** [comment]
@knsimon Wurde implementiert v1.0.0-rc2 

Probiere es einmal aus und gib mit Feedback

Es gibt ein Problem, dass Rendering braucht ca. 2-3 sec. Dies ist vermutlich nicht zu ändern, da dies  CPU abhängig ist.

**Comment by knsimon** [comment]
Super, das funktioniert tiptop! 

Im Moment werden die Formeln noch bei der kleinen Änderung und
jedem auto-save neue gerendert. Das macht den Editor etwas
träge. Stört mich aber nicht.  

Wahrscheinlich verwendest du im Moment noch das MathJax CDN. Die
2-3 Sekunden fürs Rendering stammen dann wohl eher vom Netzwerk.
Wenn ihr MathJax definitiv in die E.Tutorials integriert,
wirst du wahrscheinlich eine eigene Instanz von MathJax auf
deinem Server installieren. Vermutlich wird das Rendering dann
schneller.

Gruss
Simon

**Comment by DavidSichau** [comment]
Das mit dem Auto Save ist so gewollt, die Funktion wird zwar getrottled (200ms) aber der Nutzer soll möglichst live sehen.

Zum zweiten Punkt das liegt nicht am CDN, der wird im Cache gespeicher sodass, beim zweiten öffnen keine Latenz einen Einfluss hat. Das Problem ist die CPU. Zuerst muss alles durch den Markdown Renderer, dann durch die Erweiterungen und erst dann kann mathjax die Arbeit aufnehmen. Werde mir das noch einmal genauer anschauen.
