### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by miraamis** [Educational-Engineering/Issues#28]
Die Fenstergrösse kann nicht verändert werden und es gibt keinen Zeilenumbruch bei langen Links im IE 11 (bei Firefox ist beides kein Problem)

**Comment by DavidSichau** [comment]
Need to add 

    resizable=yes

**Comment by miraamis** [comment]
Bei Code-Abschnitten gibt es dafür unschöne Zeilenumbrüche. (Printscreen: links IE 11, rechts: Firefox)

![code ie](https://cloud.githubusercontent.com/assets/11815396/7596938/d905dd82-f8f0-11e4-9236-edb657ce3ac4.png)

**Comment by DavidSichau** [comment]
Danke, ich werde mir das am Montag anschauen.

**Comment by DavidSichau** [comment]
Wurde in Release Candidate 1.0.0-rc3 gefixed. 
Könntest du das einmal überprüfen.

**Comment by miraamis** [comment]
Fenstergrösse lässt sich nun anpassen und die Code-Abschnitte sehen gut aus. Bei langen Links gibt es noch keinen Zeilenumbruch (nur IE 11). Bei Chrome ist mir noch aufgefallen, dass das Tutorial zu hoch ist, daher der Weiter-Button ist unter der Status-Leiste in Windows 7. (siehe Printscreen)

![chrome - weiter-button](https://cloud.githubusercontent.com/assets/11815396/7684961/888b959c-fd8a-11e4-9ad9-674925ed6484.png)

**Comment by DavidSichau** [comment]
Vielen Dank.

Das Problem mit der Status-Leiste ist ein Feature von Windows 7 ist in späteren Versionen behoben (ab Win 8). Wird daher nicht gefixed.

Mit den Links habe ich es unter win 10 mit IE 11 getestet. Sobald ein Leerzeichen im Link ist wird ein Zeilenumbruch gemacht. Ansonsten nicht, da er nicht weiss wo er trennen soll. 
Kannst du dies so nachvollziehen?

**Comment by miraamis** [comment]
Ja, danke.

Liebe Grüsse
