### ISSUE TITLE
Anmeldeprozedere

### ISSUE THREAD

**Issue by faesslel** [Educational-Engineering/Issues#34]
Bei der Anmeldung ist als Sprache Spanisch als Default angegeben. Wenn das nicht geändert wird, werden nachher nur spanische Kurse (z.Z. keine) angezeigt.

**Comment by DavidSichau** [comment]
Problem kann nicht nachvollzogen werden. Welcher Browser ist betroffen?

**Comment by DavidSichau** [comment]
Problem liegt daran, das IE nicht den iso code 639-1 zurückgibt sondern den 5 letter code.
