### ISSUE TITLE
Tippfehler auf Java-Startseite

### ISSUE THREAD

**Issue by emilmueller** [Educational-Engineering/Issues#53]
Auf der Seite https://et.ethz.ch/module/8cXatz3scj8A6ywNa (Programme erstellen in Java) heisst es im Text: "Lesen Sie die kurze Einführung in die Programmierkonzepte Variablen und Datentypen mit Python." Python müsste wohl Java heissen.
Gruss emil müller

**Comment by DavidSichau** [comment]
Vielen Dank wurde ausgebessert
