### ISSUE TITLE
"Angemeldete Studenten: 0.5"

### ISSUE THREAD

**Issue by rolve** [Educational-Engineering/Issues#71]
Bei einem Termin zeigt es "0.5" angemeldete Studenten an. Ausserdem sollte es wohl "Angemeldete Gruppen" und nicht "Angemeldete Studenten" heissen.

**Comment by DavidSichau** [comment]
Um welchen Termin handelt es sich?

**Comment by rolve** [comment]
Sorry, ich finde den Termin nicht mehr, bzw. glaube ich, dass sich die 
Anzahl Studenten in der Zwischenzeit geändert hat.

**Comment by DavidSichau** [comment]
https://pele.ethz.ch/event/assi/E828GXRJ5nCkQFC9x

Vermutlich ein Problem mit personen die sich nachträglich anmelden.
