### ISSUE TITLE
Quiz questions don't support preformatted text

### ISSUE THREAD

**Issue by malisal** [Educational-Engineering/Issues#82]
We saw that it's currently not possible to create quiz questions that have preformatted texts as answers. For example, the following does not work (we tried placing the "{:.correct}" at various places.

@BEGIN@{:.panel .quiz} 
**Frage:** Lorem Ipsum

- ```
A B C D
```
- ```
A B
C D
``` {:.correct}

- ```
A B
   C D
``` 
@END@

**Comment by DavidSichau** [comment]
Questions are an extensions of markdown lists. Therefore only markdown permitted in lists are allowed. Code block.

The best way to circumvent this problem is by adapting the question accordingly.

Here an example.
https://test.et.ethz.ch/reader/8Ph2hEadjAJvP7KSw
