### ISSUE TITLE
Editor has no spellchecker

### ISSUE THREAD

**Issue by malisal** [Educational-Engineering/Issues#83]
It would be great if the editor had a spellchecker built in. Currently, there is no easy way of performing a spellcheck, other than copy-paste the text in other programs.

**Comment by DavidSichau** [comment]
Not supported by default in ace. But according to this: https://groups.google.com/forum/#!topic/ace-discuss/-dwNC_rX7R0

Should be possible to implement.

**Comment by DavidSichau** [comment]
Deployed on the test server

**Comment by malisal** [comment]
The spellcheck seems to work on some portions of the text, and not on others. How is the language of the spellchecker determined? For example, I have the language of the interface set to "English", but pretty much all the words are labeled as wrong.

![screen shot 2016-07-28 at 10 31 55](https://cloud.githubusercontent.com/assets/1385236/17206123/8e3a84d6-54ae-11e6-8027-62095b019fbb.png)

Also, once the spellchecker created the red underlines, they seem to stick around even after the text was removed.

**Comment by DavidSichau** [comment]
You can change the language of the spellchecker via the context menu. It is currently not taken from the current language settings.

The other error should be resolved in version 3.0.0-rc6.

**Comment by DavidSichau** [comment]
The behaviour for the rc7 was changed. The Spellchecker now uses the language defined in the markdown file.

**Comment by malisal** [comment]
Can you give an example of how to specify the language in markdown?

**Comment by DavidSichau** [comment]
The language of a markdown document is defined by editing the E.tutorial (https://test.et.ethz.ch/editor/ets). There you can define the language.
