### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by DavidSichau** [Educational-Engineering/Issues#84]
Currently there is no way to store previous states of the markdown.

The suggested approach is to store snapshots.

**Comment by malisal** [comment]
By snapshots, do you mean some form of simple version control?

**Comment by DavidSichau** [comment]
Yes. The editor should provide the possibility to take a snapshot from the current state and save that.

Later the editor can be restored to a snapshot.

**Comment by DavidSichau** [comment]
Is deployed on the test system.
