### ISSUE TITLE
Disable quiz answer highlighting

### ISSUE THREAD

**Issue by malisal** [Educational-Engineering/Issues#87]
It would be perfect if we could add a tag (or something) to a quiz, that would prevent the quiz from highlighting in green and red the correct and incorrect answers that the students clicked.

This would prevent the students from immediately getting the correct answers out, by simply observing the colors.

**Comment by DavidSichau** [comment]
In Version 3.1.0 the `.nohint` flag can added to a quiz to disable the highlighting. However students can still look the answers up in the source code. This is just for simple quizzes.
